init:
	nvm use 14 && npm -y init; npm i express express-graphql graphql; touch index.js
start:
	nvm use 14 && node index.js
#post: 
#	curl -X POST -H 'Content-Type: application/json' -H 'Accept: application/json'\
#	-d '{"query \\{rollDice(numDice: 10, numSides: 8)\\}" }' http://localhost:1200/graphql ; echo '\n'
